services:
  issuer_frontend:
    image: ghcr.io/eu-digital-identity-wallet/eudi-srv-web-issuing-frontend-eudiw-py/:latest
    ports:
      - "6007:5000"
    volumes:
      - /tmp/issuer_frontend/log_dev:/tmp/issuer_frontend/log_dev
    env_file:
      - .env
    restart: unless-stopped
